name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update apt
      run: sudo apt-get update

    - name: Install apt dependencies
      run: sudo apt-get -y install libpam0g libpam-dev expect

    - name: Configure CMake
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      shell: bash
      run: ctest -C $BUILD_TYPE
